apiVersion: v1
kind: Service
metadata:
  name: nexo-assist
  labels:
    app.kubernetes.io/name: nexo-assist
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexo-assist
  ports:
    - name: http
      port: 80
      targetPort: http
