#!/usr/bin/env python3
"""Extract real user messages from Claude Code session logs.

Reads all `*.jsonl` files in a Claude Code projects dir (defaults to the dir
derived from the current working directory) and emits JSON to stdout with
user messages, stripped of system noise (system-reminder tags, slash commands,
tool results, pure URLs, etc.). The LLM consumes this output and judges which
items are durable feedback — no keyword pre-filter is applied here.

Output shape (JSON):
    {
        "scanned_sessions": int,
        "total_user_messages": int,
        "kept": int,
        "skipped_files": int,
        "skipped_lines": int,
        "items": [
            {
                "session": str,         # session uuid
                "ts": str,              # ISO timestamp
                "text": str,            # the user message (truncated)
                "prior_assistant": str  # short snippet of previous assistant turn
            },
            ...
        ]
    }

Pure stdlib. No network calls. Read-only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from glob import glob
from typing import Any, Iterator

def default_projects_dir() -> str:
    """Derive the Claude Code session dir from the current working directory.

    Claude Code stores sessions under `~/.claude/projects/<slug>/`, where the
    slug is the absolute cwd with `/` replaced by `-` and a leading `-`.
    """
    cwd = os.getcwd()
    slug = "-" + cwd.lstrip("/").replace("/", "-")
    return os.path.expanduser(f"~/.claude/projects/{slug}")

# Substrings that mark a user "message" as system noise rather than real input.
SYSTEM_NOISE_PREFIXES = (
    "<system-reminder>",
    "<command-name>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<bash-stderr>",
    "<bash-stdout>",
    "<user-prompt-submit-hook>",
    "[Request interrupted",
    "Caveat: The messages below were generated by the user while running local commands",
)

# Counters for files / lines skipped due to read or parse errors.
SKIPPED: dict[str, int] = {"files": 0, "lines": 0}


def iter_jsonl(path: str) -> Iterator[dict[str, Any]]:
    try:
        fh = open(path, encoding="utf-8")
    except OSError as exc:
        print(f"warn: cannot open {path}: {exc}", file=sys.stderr)
        SKIPPED["files"] += 1
        return
    with fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError as exc:
                print(f"warn: bad JSON in {path}: {exc}", file=sys.stderr)
                SKIPPED["lines"] += 1
                continue


def extract_text(content: Any) -> str:
    """Pull plain text out of a user message's `content` field.

    Skip tool_result blocks — those are not real user input.
    """
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "tool_result":
                # Skip — it's a tool reply, not user input.
                continue
            if btype == "text":
                t = block.get("text") or ""
                if isinstance(t, str):
                    parts.append(t)
            elif btype == "image":
                continue
        return "\n".join(parts).strip()
    return ""


def is_real_user_input(text: str) -> bool:
    if not text:
        return False
    stripped = text.strip()
    if not stripped:
        return False
    # Slash command invocations — not feedback, just commands.
    if stripped.startswith("/") and "\n" not in stripped and len(stripped) < 200:
        return False
    # System-injected tags.
    for prefix in SYSTEM_NOISE_PREFIXES:
        if stripped.startswith(prefix):
            return False
    # Pure URL.
    if re.fullmatch(r"https?://\S+", stripped):
        return False
    return True


def short(s: str, n: int) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    if len(s) <= n:
        return s
    return s[: n - 1] + "…"


def assistant_snippet(msg: dict[str, Any]) -> str:
    content = msg.get("message", {}).get("content") if isinstance(msg, dict) else None
    if isinstance(content, str):
        return short(content, 220)
    if isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type")
            if btype == "text":
                parts.append(str(block.get("text") or ""))
            elif btype == "tool_use":
                name = block.get("name", "tool")
                parts.append(f"[tool_use:{name}]")
        return short(" ".join(parts), 220)
    return ""


def process_session(path: str) -> tuple[int, list[dict[str, Any]]]:
    session_id = os.path.splitext(os.path.basename(path))[0]
    user_count = 0
    items: list[dict[str, Any]] = []
    prior_assistant: str = ""
    for event in iter_jsonl(path):
        etype = event.get("type")
        if etype == "assistant":
            prior_assistant = assistant_snippet(event)
            continue
        if etype != "user":
            continue
        msg = event.get("message") or {}
        text = extract_text(msg.get("content"))
        if not is_real_user_input(text):
            continue
        user_count += 1
        items.append(
            {
                "session": session_id,
                "ts": event.get("timestamp") or "",
                "text": short(text, 800),
                "prior_assistant": prior_assistant,
            }
        )
    return user_count, items


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dir",
        default=default_projects_dir(),
        help="Claude Code projects dir (default: derived from cwd)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Process only N most recently modified session files (0 = all)",
    )
    parser.add_argument(
        "--since",
        default="",
        help="ISO date (YYYY-MM-DD). Drop items with ts < this date.",
    )
    parser.add_argument(
        "--out",
        default="-",
        help="Output path (default '-' = stdout)",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.dir):
        print(f"error: directory not found: {args.dir}", file=sys.stderr)
        return 2

    files = glob(os.path.join(args.dir, "*.jsonl"))
    files.sort(key=lambda p: os.path.getmtime(p), reverse=True)
    if args.limit > 0:
        files = files[: args.limit]

    total_users = 0
    all_items: list[dict[str, Any]] = []
    for path in files:
        users, items = process_session(path)
        total_users += users
        all_items.extend(items)

    if args.since:
        all_items = [i for i in all_items if i["ts"] >= args.since]

    all_items.sort(key=lambda i: i["ts"], reverse=True)

    out = {
        "scanned_sessions": len(files),
        "total_user_messages": total_users,
        "kept": len(all_items),
        "skipped_files": SKIPPED["files"],
        "skipped_lines": SKIPPED["lines"],
        "items": all_items,
    }
    payload = json.dumps(out, ensure_ascii=False, indent=2)
    if args.out == "-":
        sys.stdout.write(payload)
        sys.stdout.write("\n")
    else:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(payload)
        print(
            f"wrote {len(all_items)} items from {len(files)} sessions to {args.out}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
